In [3]:
#  예제 9.6-1 프로그램

import cv2
import numpy as np
import glob

# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 

# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 
                        0:CHECKERBOARD[1]].T.reshape(-1, 2)

# Extracting path of individual image stored in a given directory
images = glob.glob('../../data/calib/*.jpg')
for fname in images:
    
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    
    # Find the chess board corners
    # If desired number of corners are found, ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, None)
     
    if ret == True:
        
        objpoints.append(objp)
        
        # refining pixel coordinates for given 2d points.       
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)        
        imgpoints.append(corners2)
        
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2,ret)
    
    cv2.imshow('img',img)
    cv2.waitKey(0)

cv2.destroyAllWindows()

"""
Performing camera calibration by passing values of known 3D points (objpoints)
and corresponding pixel coordinates of detected corners (imgpoints)
"""

ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
    objpoints,  imgpoints, gray.shape[::-1],None,None)

# 실수 출력 포맷 셋팅
float_formatter = "{:7.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

print("Camera matrix : \n"), print(mtx,'\n')
print("dist : \n"), print(dist,'\n')

for i in range(len(rvecs)) :
    print("rvecs -",i)
    print(rvecs[i],'\n')

for i in range(len(tvecs)) :
    print("tvecs -",i)
    print(tvecs[i], '\n')
    


Camera matrix : 

[[ 503.82    0.00  314.22]
 [   0.00  503.21  243.51]
 [   0.00    0.00    1.00]] 

dist : 

[[   0.21   -0.43    0.00   -0.00    0.18]] 

rvecs - 0
[[  -0.31]
 [   0.15]
 [   1.58]] 

rvecs - 1
[[   0.31]
 [   0.59]
 [   1.40]] 

rvecs - 2
[[   0.33]
 [   0.56]
 [   1.40]] 

rvecs - 3
[[   0.79]
 [   0.53]
 [   1.52]] 

rvecs - 4
[[   0.43]
 [   0.68]
 [   1.34]] 

rvecs - 5
[[  -0.41]
 [  -0.72]
 [   1.36]] 

rvecs - 6
[[  -0.42]
 [  -0.77]
 [   1.34]] 

rvecs - 7
[[  -0.23]
 [  -0.05]
 [   1.52]] 

rvecs - 8
[[   0.11]
 [  -0.47]
 [   1.48]] 

rvecs - 9
[[   0.85]
 [   0.20]
 [   1.47]] 

rvecs - 10
[[  -0.45]
 [  -0.31]
 [   1.54]] 

rvecs - 11
[[  -0.70]
 [  -0.58]
 [   1.45]] 

rvecs - 12
[[  -0.30]
 [   0.18]
 [   1.57]] 

rvecs - 13
[[  -0.24]
 [   0.22]
 [   1.56]] 

tvecs - 0
[[   5.47]
 [  -1.02]
 [  12.80]] 

tvecs - 1
[[   2.55]
 [  -2.04]
 [   9.89]] 

tvecs - 2
[[   2.77]
 [  -2.72]
 [   9.47]] 

tvecs - 3
[[   1.52]
 [  -2.41]
 [   8.16]] 

tvecs - 4
[